export const clients = [
  {
    id: 'q1',
    created: '2018-05-11T13:01:04.069000Z',
    updated: '2018-05-11T13:01:04.069000Z',
    name: 'Илья',
    surname: 'Луценко',
    second_name: 'Дмитриевич',
    born: '2018-05-11T13:01:04.069000Z',
    regular: true,
    address: 'Калиновая 66/12',
    phone: '0966365260',
    diagnosis: 'asdf asf  asf',
    history:[],
    teeth:{
      tr8: null,
      tr7: null,
      tr6: null,
      tr5: null,
      tr4: null,
      tr3: null,
      tr2: null,
      tr1: null,
      tl1: null,
      tl2: null,
      tl3: null,
      tl4: null,
      tl5: null,
      tl6: null,
      tl7: null,
      tl8: null,
      br8: null,
      br7: null,
      br6: null,
      br5: null,
      br4: null,
      br3: null,
      br2: null,
      br1: null,
      bl1: null,
      bl2: null,
      bl3: null,
      bl4: null,
      bl5: null,
      bl6: null,
      bl7: null,
      bl8: null,
    },
  },
]

export const price = [
  {
    id:'pr1',
    active:true,
    q:'1 ед.',
    price:50,
    label:'Программа «АнтиСПИД»',
  },
  {
    id:'pr2',
    active:true,
    q:'1 посещение',
    price:70,
    label:'Осмотр (первичное посещение)',
  },
  {
    id:'pr3',
    active:true,
    q:'1 посещение',
    price:55,
    label:'Консультация стоматолога',
  },
  {
    id:'pr4',
    active:true,
    q:'1 инъекция',
    price:55,
    label:'Проведение анестезии лидокаином',
  },
  {
    id:'pr5',
    active:true,
    q:'1 инъекция',
    price:95.00,
    label:'Проведение анестезии импортным анестетиком',
  },
  {
    id:'pr6',
    active:true,
    q:'1 инъекция',
    price:50.00,
    label:'Проведение аппликационной анестезии лидокаином',
  },
  {
    id:'pr7',
    active:true,
    q:'1 зуб',
    price:80.00,
    label:'Лечение кариеса (поверхностного)',
  },
  {
    id:'pr8',
    active:true,
    q:'1 зуб',
    price:100.00,
    label:'Лечение кариеса (среднего)',
  },
  {
    id:'pr9',
    active:true,
    q:'1 зуб',
    price:130.00,
    label:'Лечение кариеса (глубокого)',
  },
  {
    id:'pr10',
    active:true,
    q:'1 канал',
    price:200.00,
    label:'Лечение пульпита и периодонтита',
  },
  {
    id:'pr11',
    active:true,
    q:'1 зуб',
    price:150.00,
    label:'Лечение пульпита ампутационным комбинорованным методом',
  },
  {
    id:'pr12',
    active:true,
    q:'1 зуб',
    price:90.00,
    label:'Наложение девитализирующей пасты',
  },
  {
    id:'pr13',
    active:true,
    q:'1 канал',
    price:55.00,
    label:'Пломбирование корневых каналов(отечественными материалами)',
  },
  {
    id:'pr14',
    active:true,
    q:'1 канал',
    price:150,
    label:'Пломбирование корневых каналов(импортными материалами)',
  },
  {
    id:'pr15',
    active:true,
    q:'1 канал',
    price:130,
    label:'Пломбирование корневых каналов(временная пломбировка корневых каналов)',
  },
  {
    id:'pr16',
    active:true,
    q:'1 канал',
    price:150.00,
    label:'Распломбирование каналов зуба',
  },
  {
    id:'pr17',
    active:true,
    q:'1 канал',
    price:180.00,
    label:'Извлечение инородного тела из канала, анчерн. штифта',
  },
  {
    id:'pr18',
    active:true,
    q:'1 канал',
    price:150.00,
    label:'Прохождение склерозированного каналаТрепанация интактного зуба',
  },
  {
    id:'pr19',
    active:true,
    q:'1 зуб',
    price:70.00,
    label:'Трепанация интактного зуба',
  },
  {
    id:'pr20',
    active:true,
    q:'1 посещение',
    price:80.00,
    label:'Повторное посещение при лечении пульпита и периодонтита с обработкой каналов',
  },
  {
    id:'pr21',
    active:true,
    q:'1 пломба',
    price:60.00,
    label:'Снятие пломбы',
  },
  {
    id:'pr22',
    active:true,
    q:'1 ед.',
    price:60.00,
    label:'Диатермокоагуляция пульпы, десневого сосочка',
  },
  {
    id:'pr23',
    active:true,
    q:'1 пл.',
    price:100.00,
    label:'Пломба из Цемента',
  },
  {
    id:'pr24',
    active:true,
    q:'1 пл.',
    price:150.00,
    label:'Пломба из Стеклоиономерные цементы',
  },
  {
    id:'pr25',
    active:true,
    q:'1 четв.',
    price:145.00,
    label:'Фотополимерные материалы - Революшен',
  },
  {
    id:'pr26',
    active:true,
    q:'1 четв.',
    price:320.00,
    label:'Фотополимерные материалы - Харизма',
  },
  {
    id:'pr261',
    active:true,
    q:'1 четв.',
    price:400.00,
    label:'Фотополимерные материалы - Эстелайт',
  },
  {
    id:'pr27',
    active:true,
    q:'1 четв.',
    price:390.00,
    label:'Реставрация коронки зуба материалом - Харизма',
  },
  {
    id:'pr28',
    active:true,
    q:'1 четв.',
    price:500.00,
    label:'Реставрация коронки зуба материалом - Эстелайт',
  },
  {
    id:'pr29',
    active:true,
    q:'1 ед.',
    price:50.00,
    label:'Прокладка - Триоксидент',
  },
  {
    id:'pr30',
    active:true,
    q:'1 ед.',
    price:80.00,
    label:'Прокладка - Гидроксид Са',
  },
  {
    id:'pr31',
    active:true,
    q:'1 ед.',
    price:30.00,
    label:'Прокладка - Джен-лайн',
  },
  {
    id:'pr32',
    active:true,
    q:'1 ед.',
    price:220.00,
    label:'Закрытие перфорации коронки, корня',
  },
  {
    id:'pr34',
    active:true,
    q:'1 пл.',
    price:75.00,
    label:'Применение коффердама',
  },
  {
    id:'pr35',
    active:true,
    q:'1 см.',
    price:120.00,
    label:'Шинирование зубов: Стекловолоконная нить',
  },
  {
    id:'pr36',
    active:true,
    q:'1 ед.',
    price:180.00,
    label:'Стекловолоконный штифт',
  },
  {
    id:'pr37',
    active:true,
    q:'1 зуб',
    price:35.00,
    label:'Удаление зубных отложений',
  },
  {
    id:'pr38',
    active:true,
    q:'1 зуб',
    price:30.00,
    label:'Медикаментозная обработка десневых карманов, аппликация лекарственных трав',
  },
  {
    id:'pr39',
    active:true,
    q:'1 зуб',
    price:90.00,
    label:'Кюретаж пародонтальных карманов',
  },
  {
    id:'pr40',
    active:true,
    q:'1 зуб',
    price:110.00,
    label:'Вскрытие пародонтального абсцесса',
  },
  {
    id:'pr41',
    active:true,
    q:'1 зуб',
    price:70.00,
    label:'Избирательное пришлифование зубов',
  },
  {
    id:'pr42',
    active:true,
    q:'1 инъекц.',
    price:60.00,
    label:'Инъекция лекарственных веществ в десну',
  },
  {
    id:'pr43',
    active:true,
    q:'1 проц',
    price:60.00,
    label:'Медикаментозная обработка слизистой при стоматитах',
  },

  {
    id:'pr44',
    active:true,
    q:'1 пломб',
    price:80.00,
    label:'Полировка ранее поставленных фотополимерных пломб',
  },

  {
    id:'pr45',
    active:true,
    q:'1 зуб',
    price:40.00,
    label:'Покрытие лаком зубов',
  },

  {
    id:'pr46',
    active:true,
    q:'1 проц.',
    price:500.00,
    label:'Профессиональная чистка зубов',
  },

  {
    id:'pr47',
    active:true,
    q:'1 проц.',
    price:350.00,
    label:'Внутриканальное отбеливание зубов',
  },

]